# Generated by Django 6.0.4 on 2026-09-05 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0003_authoredpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="authoredpost",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_posts",
                to="testapp.folder",
            ),
        ),
    ]
