# Generated by Django 6.0.4 on 2026-09-13 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0006_folder_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColumnlessIdentityFolder",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("testapp.folder",),
        ),
        migrations.CreateModel(
            name="MissingLookupIdentityFolder",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("testapp.folder",),
        ),
        migrations.CreateModel(
            name="NonExpressionIdentityFolder",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("testapp.folder",),
        ),
        migrations.CreateModel(
            name="PrimarySluggedPost",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("testapp.sluggedpost",),
        ),
        migrations.CreateModel(
            name="PropertyIdentityFolder",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("testapp.folder",),
        ),
        migrations.CreateModel(
            name="SubjectContainer",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("testapp.sluggedpost",),
        ),
        migrations.CreateModel(
            name="VirtualFolder",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("testapp.folder",),
        ),
        migrations.CreateModel(
            name="VirtualPost",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("testapp.post",),
        ),
        migrations.AddField(
            model_name="authoredpost",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="authoredpost",
            name="dismissed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="authoredpost",
            name="role",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="folder",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="post",
            name="collections",
            field=models.ManyToManyField(
                blank=True, related_name="collected_posts", to="testapp.folder"
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sluggedpost",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="SlugReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="testapp.sluggedpost",
                        to_field="slug",
                    ),
                ),
            ],
        ),
    ]
