# Generated by Django 6.0.4 on 2026-09-29 18:51

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0010_text_identity_fixtures"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authoredpost",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="backingbinding",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="backingdocument",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="backingentry",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="backingotherdocument",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="backingproject",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="backingqueue",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="backinground",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="backingtask",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="columnlessidentityfolder",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="encodedfolder",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="encodedpost",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="encodedprimarypost",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="folder",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="missinglookupidentityfolder",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="nativeparentlinkedchild",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="nativeparentlinkedrecord",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="nativeparentlinkedresource",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="nonexpressionidentityfolder",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="parentlinkedchild",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="parentlinkedrecord",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="parentlinkedresource",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="primarysluggedpost",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="propertyidentityfolder",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="sluggedpost",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="slugreference",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="subjectcontainer",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="textidentityfolder",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="textidentitypost",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="textidentityprimarypost",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="virtualfolder",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="virtualpost",
            options={"base_manager_name": "_rebac_base", "default_manager_name": "objects"},
        ),
        migrations.AlterModelManagers(
            name="authoredpost",
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="backingbinding",
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="backingdocument",
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="backingentry",
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="backingotherdocument",
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="backingproject",
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="backingqueue",
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="backinground",
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="backingtask",
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="encodedfolder",
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="encodedpost",
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="encodedprimarypost",
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="folder",
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="nativeparentlinkedchild",
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="nativeparentlinkedrecord",
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="nativeparentlinkedresource",
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="parentlinkedchild",
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="parentlinkedrecord",
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="parentlinkedresource",
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="post",
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="sluggedpost",
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="slugreference",
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="textidentityfolder",
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="textidentitypost",
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="textidentityprimarypost",
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
