# Generated by Django 6.0.8 on 2026-10-01 11:53

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0014_directedpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeclaredBasePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "folder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="declared_posts",
                        to="testapp.folder",
                    ),
                ),
            ],
            options={
                "base_manager_name": "system_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("system_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
