# Generated by Django 6.0.4 on 2026-10-02 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0015_declared_base_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="textidentityfolder",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="testapp.textidentityfolder",
            ),
        ),
    ]
