# Generated by Django 6.0.4 on 2026-10-02 09:07

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0017_coded_folder"),
    ]

    operations = [
        migrations.CreateModel(
            name="NativeParentLinkedBranch",
            fields=[
                (
                    "nativeparentlinkedresource_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="testapp.nativeparentlinkedresource",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="testapp.nativeparentlinkedbranch",
                    ),
                ),
            ],
            options={
                "base_manager_name": "_rebac_base",
                "default_manager_name": "objects",
            },
            bases=("testapp.nativeparentlinkedresource",),
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="NativeParentLinkedNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="testapp.nativeparentlinkedbranch",
                    ),
                ),
            ],
            options={
                "base_manager_name": "_rebac_base",
                "default_manager_name": "objects",
            },
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
