# Generated by Django 6.0.4 on 2026-10-02 14:16

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0018_parent_linked_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="PinnedPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
            ],
            options={
                "base_manager_name": "_rebac_base",
                "default_manager_name": "objects",
            },
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PostPin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=100)),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="testapp.folder"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="testapp.pinnedpost"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pinnedpost",
            name="folders",
            field=models.ManyToManyField(
                related_name="pinned_posts", through="testapp.PostPin", to="testapp.folder"
            ),
        ),
    ]
