# Generated by Django 6.0.4 on 2026-10-06 09:42

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0020_attachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shelf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=50)),
            ],
            options={
                "base_manager_name": "_rebac_base",
                "default_manager_name": "objects",
            },
            managers=[
                ("_rebac_base", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
